[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"
Oceananigans = "9e8cae18-63c1-5223-a75c-80ca9d6e9a09"
Oceanostics = "d0ccf422-c8fb-49b5-a76d-74acdde946ac"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
SeawaterPolynomials = "d496a93d-167e-4197-9f49-d3af4ff8fe40"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
